let g:coc_global_extensions = [
  \ 'coc-lists',
  \ 'coc-marketplace',
  \ 'coc-jedi',
  \ 'coc-git',
  \ 'coc-fzf-preview',
  \ 'coc-explorer',
  \ 'coc-snippets',
  \ 'coc-vimlsp',
  \ 'coc-yank',
  \ 'coc-sh',
  \ 'coc-python',
  \ 'coc-docker',
  \ 'coc-clangd',
  \ 'coc-yaml',
  \ 'coc-json',
  \ 'coc-actions',
  \ 'coc-tasks',
  \ 'coc-floaterm',
  \ 'coc-bookmark',
  \ 'coc-prettier',
  \ 'coc-xml',
  \ 'coc-vimtex',
  \ 'coc-bibtex',
  \ 'coc-highlight'
  \ ]

  "\ 'coc-tabnine',
