vim.notify = require("notify")
--require("core.completion")
require("core.telescope")
require("core.git-worktree")
require("core.gitsigns")
require("core.symbols-outline")
require("core.lualine")
require("core.trouble")
require("core.todo-comments")
require("core.nvim-toggleterm")
