require("core.telescope")
require("core.git-worktree")
require("core.gitsigns")
require("core.symbols-outline")
require("core.lualine")
require("core.nvim-toggleterm")
require("core.trouble")
--require("core.galaxyline-config")
